[tool.poetry]
name = "puepy"
version = "0.1.0"
description = ""
authors = ["Ken Kinder <ken+github@kkinder.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pypugjs = "^5.9.12"
jinja2 = "^3.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

